#!/usr/bin/env python3
import sympy as sp, json
from pathlib import Path

k,th,r=sp.symbols('k theta rho', real=True)
C=sp.Matrix([[k,0,k*th*(1-r)],[1-k,1,(1-k*th)*(1-r)],[0,0,r]])
nu,R,T=sp.symbols('nu R T', real=True)
y=sp.Matrix([nu,R,T]); yp=sp.simplify(C*y)

m=nu+R+T
a=(k-r)*nu+k*th*(1-r)*T
checks={}
checks['ledger_mode']=sp.simplify(sum(yp)-m)==0
checks['kappa_mode']=sp.simplify((k-r)*yp[0]+k*th*(1-r)*yp[2]-k*a)==0
checks['rho_mode']=sp.simplify(yp[2]-r*T)==0

phi=(1+sp.sqrt(5))/2
q=sp.simplify(phi/2)
checks['golden_gap']=sp.simplify(q**2-q**3-sp.Rational(1,8))==0

m11,m22,m33,m12,m13,m23=sp.symbols('m11 m22 m33 m12 m13 m23')
M=sp.Matrix([[m11,m12,m13],[m12,m22,m23],[m13,m23,m33]])
E=sp.expand(C.T*M*C-M)
checks['inv_step_m12']=sp.simplify(E[0,1]-(k-1)*(m12-m22))==0
checks['inv_step_m11']=sp.simplify(E[0,0].subs({m12:m22})-(k-1)*(k+1)*(m11-m22))==0
checks['inv_step_m23']=sp.simplify(E[1,2]+(r-1)*(k*m12*th-k*m22*th+m22-m23))==0
red={m12:m22,m11:m22,m23:m22}
checks['inv_step_m13']=sp.simplify(E[0,2].subs(red)-(m13-m22)*(k*r-1))==0
red2={**red,m13:m22}
checks['inv_step_m33']=sp.simplify(E[2,2].subs(red2)+(r-1)*(r+1)*(m22-m33))==0
checks['ledger_square_invariant']=sp.simplify(C.T*sp.ones(3)*C-sp.ones(3))==sp.zeros(3)

mu,v3,beta,E6,Rstar,I2=sp.symbols('mu v3 beta E6 Rstar I2', nonzero=True)
Delta=4*mu**3-27*beta*v3**2
checks['A2_discriminant_weight6']=sp.simplify(Delta.subs({mu:q**2*mu,v3:q**3*v3})-q**6*Delta)==0
checks['Rstar_coscaled_adapter_weight2']=sp.simplify((q**6*E6)/(q**4*Rstar**4)-q**2*(E6/Rstar**4))==0
checks['I2_inverse_adapter_weight2']=sp.simplify((q**6*E6)/(q**4*I2**2)-q**2*(E6/I2**2))==0

possible=[]
for e6 in range(1,3):
  for i2 in range(0,3):
   for j3 in range(0,3):
    for d in range(0,3):
     for u in range(0,3):
      if 6*e6+2*i2+3*j3+2*d+2*u==2:
       possible.append((e6,i2,j3,d,u))
checks['polynomial_weight6_to2_no_go']=(possible==[])

x=sp.symbols('x', positive=True)
checks['cube_root_derivative_diverges']=sp.limit(sp.diff(x**sp.Rational(1,3),x),x,0,dir='+')==sp.oo

status='PASS' if all(bool(v) for v in checks.values()) else 'FAIL'
certificate={
 'phase':'v20-graded-nonlinear-and-quotient-H1',
 'status':status,
 'checks':checks,
 'quadratic_sector':{
   'C2_even_dimension':6,
   'basis':['nu^2','R3^2','T3^2','nu*R3','nu*T3','R3*T3'],
   'golden_weight':6,
   'router_covariant_multipliers':['1','kappa','rho','kappa^2','kappa*rho','rho^2'],
   'unique_exact_router_invariant':'M3^2=(nu+R3+T3)^2'
 },
 'weight6_to2':{
   'same_weight_target':'A2 discriminant',
   'regular_polynomial_adapter':'REFUTED',
   'Rstar_inverse_fourth':'CONDITIONAL_IF_RSTAR_COSCALES',
   'I2_inverse_square':'LOCAL_AWAY_FROM_I2_ZERO',
   'cube_root':'WEIGHT_CORRECT_BUT_NOT_C1_AT_ZERO',
   'source_native_global_adapter':'NT_NOT_FOUND'
 },
 'quotient_H1':{
   'source_Gamma_old_definition':'Gamma={U in GL3(Z) | f o U ~ f}; tautological under the source equivalence definition if read literally',
   'orbifold_formula':'H1_orb([H/Gamma];F2)=Hom(Gamma,C2) because H is contractible',
   'coarse_formula':'H1_coarse(H/Gamma;F2)=Hom(Gamma/N_stab,C2) under standard proper-action hypotheses',
   'literal_GL3_orbifold':'F2 generated by determinant sign',
   'literal_GL3_coarse':'NT until point stabilizers are known',
   'instance_specific_Gamma_f':'NT until a presentation/generators/stabilizers are supplied'
 },
 'statuses':{
   'quadratic_C2_golden_classification':'PROVEN_EXACT',
   'unique_router_invariant_quadratic':'PROVEN_EXACT_CONTRACTIVE',
   'weight6_A2_coupling':'PROVEN_CONSTRUCTED',
   'global_regular_polynomial_6_to_2':'REFUTED',
   'global_source_native_6_to_2_adapter':'NT',
   'quotient_orbifold_H1_formula':'PROVEN_GENERAL',
   'quotient_coarse_H1_formula':'PROVEN_GENERAL_CONDITIONAL_ON_STANDARD_ACTION_HYPOTHESES',
   'specific_project_quotient_H1_numeric':'NT_GAMMA_AND_STABILIZERS_NOT_SPECIFIED_COHERENTLY',
   'literal_source_GL3_orbifold_H1':'F2_CONDITIONAL_LITERAL_READING'
 },
 'guards':[
   'C2 and golden covariance alone leave a six-dimensional quadratic sector; exact router invariance selects only the square of the conserved ledger.',
   'A weight-6 object cannot polynomially produce a weight-2 output without a negative-weight carrier.',
   'Dividing by R_*^4 is golden-equivariant only if R_* is itself co-scaled; the fixed locking radius does not provide that.',
   'Dividing by I2^2 is singular exactly at the A2 critical set I2=0.',
   'The old source definition of Gamma is ambiguous/tautological when combined with the source definition of integral equivalence; do not silently identify the intended automorphism group with GL3(Z).',
   'Orbifold/action-groupoid H1 and coarse-quotient H1 can differ when stabilizers are nontrivial.'
 ]
}
Path('/mnt/data/graded_nonlinear_quotient_H1_v20_certificate.json').write_text(json.dumps(certificate,indent=2,ensure_ascii=False))
print(json.dumps(certificate,indent=2,ensure_ascii=False))
raise SystemExit(0 if status=='PASS' else 1)
