#!/usr/bin/env python3
from pathlib import Path
import json,hashlib,subprocess,sys
B=Path(__file__).resolve().parent
checks=[]
def ck(name,cond,detail=None):
 checks.append({'name':name,'pass':bool(cond),'detail':detail})
 if not cond: raise AssertionError(name)
def J(n):return json.load(open(B/n))
def sha(n):return hashlib.sha256((B/n).read_bytes()).hexdigest()
# lightweight exact replay for the expensive period certificate
r=subprocess.run([sys.executable,str(B/'verify_gamma3_radius5_iterated_certificate_v51.py')],cwd=B,capture_output=True,text=True,timeout=120)
ck('iterated_lightweight_replay_returncode',r.returncode==0,r.stderr[-500:])
# Formal context
fc=J('v51_FORMAL_CONTEXT_ATTESTATION.json');ck('formal_context_lock',fc['status']=='PASS-FORMAL-CONTEXT-LOCK');ck('formal_context_nine_docs',len(fc['documents'])==9);ck('no_silent_substitution_guard','never silently substituted' in fc['discipline']['source_byte_guard']);ck('nt_not_binarized','not binarized' in fc['discipline']['nt_guard'])
# Source Selling carrier
car=J('selling_source_axis_centre_carrier_v51.json');st=J('selling_source_axis_centre_stabilizers_v51.json');ls=J('selling_source_HC_local_star_signatures_v51.json')
ck('source_C6_status',car['status'].startswith('PROVEN-SOURCE'));ck('six_axes',len(car['axes'])==6);ck('six_centres',len(car['centres'])==6);ck('centre_coordinates',[(c['q'],c['r']) for c in car['centres']]==[('1','0'),('1','1/4'),('2/3','1/3'),('0','1/3'),('-2/3','1/9'),('-2/3','0')]);ck('six_stabilizers',len(st['centres'])==6);ck('all_stabilizers_V4',all(c['stabilizer_order']==4 and c['stabilizer_abstract']=='C2 x C2' for c in st['centres']));ck('six_local_stars',len(ls['centres'])==6)
# Raster guards
rg=J('selling_raster_central_bold_cycle_gate_v51.json');pr=J('selling_source_raster_projective_bold_cycle_audit_v51.json');ri=J('selling_raster_HC_signature_identifiability_v51.json')
ck('raster_cycle_16',rg['cycle_node_count']==16 and rg['cycle_edge_count']==16);ck('raster_unique_binding_NT','NT' in rg['decision']['unique_binding_of_six_HC_to_cycle_nodes']);ck('projective_96096',pr['candidate_count']==96096);ck('projective_diagnostic_only',pr['decision']=='DIAGNOSTIC-ONLY/NO-HISTORICAL-PROMOTION');ck('best_nodes_stable',pr['best']['nodes']==['N088','N105','N099','N103','N106','N109']);ck('table_identifiability_nogo',ri['status']=='PROVEN-RASTER-TABLE-IDENTIFIABILITY-NO-GO');ck('historical_labels_unpopulated',sum(ri[k] for k in ['populated_historical_axis_labels_in_segments','populated_historical_wall_labels_in_segments','populated_historical_form_labels_in_fields','populated_historical_node_ids'])==0);ck('raster_candidates_12',ri['candidate_count']==12);ck('raster_six_subsets_924',ri['six_subset_count_under_this_necessary_condition']==924)
# 2-primary carriers
tor=J('selling_torsion_support_bockstein_pairings_v51.json');ck('torsion_status',tor['status'].startswith('PASS-EXACT'));ck('Binet_tau_28_edges',tor['systems']['Binet']['tau_edge_orbit_support_count']==28);ck('Ad_tau_28_edges',tor['systems']['Ad']['tau_edge_orbit_support_count']==28);ck('cross_support_7',tor['cross_system']['common_edge_support_count']==7);ck('support_overlap_not_pairing',tor['cross_system']['status']=='SUPPORT-INTERSECTION-ONLY/NOT-A-COHOMOLOGICAL-PAIRING');ck('V48_transfer_index_2',tor['binet_degree2_transfer_defect']['transfer_index']==2);ck('Binet_tau_V48_pairing_zero',tor['binet_degree2_transfer_defect']['pairing_with_Binet_H1_tau']['value']==[0]);ck('three_2primary_carriers_separate','DO-NOT-IDENTIFY' in tor['binet_degree2_transfer_defect']['separation'])
# Gamma radius 5
sup=J('gamma3_radius5_support_gate_v51.json');qc=J('gamma3_radius5_quotient_cycle_v51.json');ng=J('gamma3_radius5_fourfiber_nogo_v51.json');lat=J('gamma3_radius5_residual_projection_lattice_v51.json');it=J('gamma3_radius5_iterated_kernel_correction_v51.json');itr=J('gamma3_radius5_iterated_kernel_replay_v51.json')
ck('B5_size_78944',sup['ball_size']==78944);ck('mod4_image_382',sup['mod4_image_size']==382);ck('mod4_new_depth5_126',sup['mod4_new_profile']['5']==126);ck('character_collisions_zero',sup['character_collision_count']==0);ck('quotient_cycle_deterministic',qc['status']=='PROVEN-EXACT-DETERMINISTIC-FINITE-QUOTIENT-CYCLE');ck('quotient_cycle_4_terms',qc['quotient_cycle_term_count']==4);ck('target_projection_1',qc['target_projection']=='1');ck('canonical_section_not_integral_lift',qc['chosen_representatives_form_integral_lift'] is False);ck('canonical_residual_96',qc['chosen_representatives_actual_group_ring_boundary_nonzero_terms']==96);ck('fourfiber_nogo',ng['status']=='PROVEN-EXACT-FOUR-FIBER-RATIONAL-NO-GO');ck('fourfiber_596_unknowns',ng['unknowns']==596);rr=ng['rank_certificates_mod_p'][0];ck('fourfiber_rank_596_597',rr['rank_A']==596 and rr['rank_aug']==597);ck('residual_matrix_96x637',lat['matrix_shape']==[96,637]);ck('residual_rank_64',lat['rank_Q']==64 and lat['rank_aug_Q']==64);ck('residual_lattice_saturated',lat['smith_nonunit_factors']==[]);ck('local_integral_correction_exists',lat['residual_projection_has_integral_solution'] and lat['one_rational_solution_common_denominator']==1 and lat['one_rational_solution_nonzero_directions']==4);ck('iterated_period_detected',it['residual_period_detected'] is True);ck('iterated_not_lift',it['integral_lift_found'] is False);ck('iterated_final_96',it['final_residual_count']==96 and it['final_residual_l1']==96);ck('period_replay_pass',itr['status']=='PASS-EXACT-LIGHTWEIGHT-ITERATED-CERTIFICATE-REPLAY' and itr['period_repeats_step']==2)
# global status checkpoint
m=J('v51_MATH_CHECKPOINT.json');ck('math_gate_pass_explicit_NT',m['math_gate']=='PASS-WITH-EXPLICIT-NT-FRONTIERS');ck('raster_binding_remains_NT',m['selling_source']['raster_binding'].startswith('NT/'));ck('global_B5_lift_remains_NT',m['gamma3_radius5']['global_integral_lift_in_B5']=='NT');ck('no_global_radius5_nogo_claimed',m['gamma3_radius5']['global_radius5_no_go']=='NT-NOT-PROVEN');ck('R2PURE17_separated',m['retained_separations']['R2PURE13_to_SellingDeck17']=='SEPARATED/PENDING-MORPHISM');ck('fig2_6_pending_source',m['retained_separations']['figures_2_to_6'].startswith('PENDING-SOURCE'))
artifacts=['v51_FORMAL_CONTEXT_ATTESTATION.json','v51_MATH_CHECKPOINT.json','selling_source_axis_centre_carrier_v51.json','selling_source_axis_centre_stabilizers_v51.json','selling_source_HC_local_star_signatures_v51.json','selling_raster_central_bold_cycle_gate_v51.json','selling_source_raster_projective_bold_cycle_audit_v51.json','selling_raster_HC_signature_identifiability_v51.json','selling_torsion_support_bockstein_pairings_v51.json','gamma3_radius5_support_gate_v51.json','gamma3_radius5_quotient_cycle_v51.json','gamma3_radius5_fourfiber_nogo_v51.json','gamma3_radius5_residual_projection_lattice_v51.json','gamma3_radius5_iterated_kernel_correction_v51.json','gamma3_radius5_iterated_kernel_replay_v51.json']
report={'version':'v51','status':'PASS','publication_state':'MATH-CHECKPOINT/PRESEAL/NONPUBLISHABLE','checks_passed':sum(c['pass'] for c in checks),'checks_total':len(checks),'checks':checks,'artifact_sha256':{n:sha(n) for n in artifacts},'guard':'v50 remains CLOSED/APPEND-ONLY. v51 positive and bounded-negative claims pass; raster HC binding and global radius-5 integral CHIRES14 lift remain explicitly NT.'}
p=B/'v51_frontier_checkpoint_verification.json';p.write_text(json.dumps(report,indent=2,sort_keys=True)+'\n')
print(json.dumps({k:report[k] for k in ['status','checks_passed','checks_total','publication_state']},indent=2));print('sha256',sha('v51_frontier_checkpoint_verification.json'))
